site_name: Awesome Python
site_url: https://awesome-python.com
site_description: A curated list of awesome Python frameworks, libraries and software
site_author: Vinta Chen
repo_name: vinta/awesome-python
repo_url: https://github.com/vinta/awesome-python
strict: false
theme:
  name: material
  palette:
    primary: red
    accent: pink
nav:
  - "Life is short, you need Python.": "README.md"
